creation_rules:
  - path_regex: .*.yml
    encrypted_regex: ^(password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|external-dns.alpha.kubernetes.io/target)$
    age: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427,age1n6davtvnaxdmt4qqjmj00krkqpt47r5fg49hld5v00ly4ldjyels3wxmfa