apiVersion: v1
kind: Namespace
metadata:
    name: kube-prometheus-stack
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEZrait2TVNhd0FOcW9E
            ME5pTGp4blJ0ZGlWK3dKM3lTejRVWEJ3MTI0CnhHa0dRdnFocTZ1bTIwc1F2cUJR
            L3Z1b2tLdmw1enJxR1hqR1pNcEk3elUKLS0tIGF2dWlFUmNicExiWEFCYWNmbHpX
            c0pMdU81YzdQc2czOXJLb2RsM3hOWkEKN9S5JMJAl6Ntet3v1m0mMIBcOWZekhaQ
            6a0gIcE0uY527K5PJUkgicAy/vkXIu7C+T33CBFpimtZOGFa4mFAOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArajFYSXZWc0JoQ2JTeC85
            MDl0ZzdHLzExUzNRckViM3A2SWxuTHJrUkJVCmZ2cWc5UFpSbTdBVmdMdVdCNWNz
            aEtBc1hWbCtFemlXb3BFY0VHSDh1emsKLS0tIElOeTB2RDRMVTcyUE9lN3pKcnV5
            QXdZSmkvRzlSZFNxVjRtNE81dTVMNnMKNPyKL42GxpjGLUVCLk5Nmfmfgmbei+Nq
            xOKVI7EUomcqjjkd+bKB13aVQWj93h7aV7wyqnu9RDxDX8VrFYrWgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T19:25:18Z"
    mac: ENC[AES256_GCM,data:pHV/+hk3JgVeiCAxIZDrLcb9EBEjEP0hDNJ9PwhX4S4fJcr6ScrQ+qim0R8y6pwkLILeUjmK1Gzr+WHe+zA5WH125q/Vpy7merlOOu7+PCl7n4JQjz9SG/mmc2JY4mfnLjCxNSADQLEGSa5/xxpAwXjgz1lbS1cCDyoLbxwcBfY=,iv:73wSVdPtmpEuVGm2nn7TaiLfBRZ8yNPvb585nAmD8Bo=,tag:OcDSyzmG9EpXx+wvCaWrwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://prometheus-community.github.io/helm-charts
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEZrait2TVNhd0FOcW9E
            ME5pTGp4blJ0ZGlWK3dKM3lTejRVWEJ3MTI0CnhHa0dRdnFocTZ1bTIwc1F2cUJR
            L3Z1b2tLdmw1enJxR1hqR1pNcEk3elUKLS0tIGF2dWlFUmNicExiWEFCYWNmbHpX
            c0pMdU81YzdQc2czOXJLb2RsM3hOWkEKN9S5JMJAl6Ntet3v1m0mMIBcOWZekhaQ
            6a0gIcE0uY527K5PJUkgicAy/vkXIu7C+T33CBFpimtZOGFa4mFAOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArajFYSXZWc0JoQ2JTeC85
            MDl0ZzdHLzExUzNRckViM3A2SWxuTHJrUkJVCmZ2cWc5UFpSbTdBVmdMdVdCNWNz
            aEtBc1hWbCtFemlXb3BFY0VHSDh1emsKLS0tIElOeTB2RDRMVTcyUE9lN3pKcnV5
            QXdZSmkvRzlSZFNxVjRtNE81dTVMNnMKNPyKL42GxpjGLUVCLk5Nmfmfgmbei+Nq
            xOKVI7EUomcqjjkd+bKB13aVQWj93h7aV7wyqnu9RDxDX8VrFYrWgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T19:25:18Z"
    mac: ENC[AES256_GCM,data:pHV/+hk3JgVeiCAxIZDrLcb9EBEjEP0hDNJ9PwhX4S4fJcr6ScrQ+qim0R8y6pwkLILeUjmK1Gzr+WHe+zA5WH125q/Vpy7merlOOu7+PCl7n4JQjz9SG/mmc2JY4mfnLjCxNSADQLEGSa5/xxpAwXjgz1lbS1cCDyoLbxwcBfY=,iv:73wSVdPtmpEuVGm2nn7TaiLfBRZ8yNPvb585nAmD8Bo=,tag:OcDSyzmG9EpXx+wvCaWrwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
            version: '*'
    interval: 1m0s
    values:
        grafana:
            grafana.ini:
                server:
                    domain: grafana.core-k8s.phorge.fr
                    root_url: https://grafana.core-k8s.phorge.fr/
            enabled: true
            adminPassword: ENC[AES256_GCM,data:MOv/tSf5qDmEY00mOBCRaAYosff9Zalx,iv:ATwc+XRIm1bKGVwUA3ivawY4hjs24YIdVsIiCE06a1k=,tag:qRv+Eee6JpzFxg5je+hsjA==,type:str]
            service:
                type: ClusterIP
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - grafana.core-k8s.phorge.fr
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.core-k8s.phorge.fr
            persistence:
                enabled: true
                accessModes:
                    - ReadWriteOnce
                size: 1Gi
        prometheus:
            prometheusSpec:
                retention: 15d
                serviceMonitorSelector: {}
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEZrait2TVNhd0FOcW9E
            ME5pTGp4blJ0ZGlWK3dKM3lTejRVWEJ3MTI0CnhHa0dRdnFocTZ1bTIwc1F2cUJR
            L3Z1b2tLdmw1enJxR1hqR1pNcEk3elUKLS0tIGF2dWlFUmNicExiWEFCYWNmbHpX
            c0pMdU81YzdQc2czOXJLb2RsM3hOWkEKN9S5JMJAl6Ntet3v1m0mMIBcOWZekhaQ
            6a0gIcE0uY527K5PJUkgicAy/vkXIu7C+T33CBFpimtZOGFa4mFAOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArajFYSXZWc0JoQ2JTeC85
            MDl0ZzdHLzExUzNRckViM3A2SWxuTHJrUkJVCmZ2cWc5UFpSbTdBVmdMdVdCNWNz
            aEtBc1hWbCtFemlXb3BFY0VHSDh1emsKLS0tIElOeTB2RDRMVTcyUE9lN3pKcnV5
            QXdZSmkvRzlSZFNxVjRtNE81dTVMNnMKNPyKL42GxpjGLUVCLk5Nmfmfgmbei+Nq
            xOKVI7EUomcqjjkd+bKB13aVQWj93h7aV7wyqnu9RDxDX8VrFYrWgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T19:25:18Z"
    mac: ENC[AES256_GCM,data:pHV/+hk3JgVeiCAxIZDrLcb9EBEjEP0hDNJ9PwhX4S4fJcr6ScrQ+qim0R8y6pwkLILeUjmK1Gzr+WHe+zA5WH125q/Vpy7merlOOu7+PCl7n4JQjz9SG/mmc2JY4mfnLjCxNSADQLEGSa5/xxpAwXjgz1lbS1cCDyoLbxwcBfY=,iv:73wSVdPtmpEuVGm2nn7TaiLfBRZ8yNPvb585nAmD8Bo=,tag:OcDSyzmG9EpXx+wvCaWrwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
