apiVersion: v1
kind: Namespace
metadata:
    name: kube-prometheus-stack
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NU51RElrd29xWDM2T0hr
            UEc5cVVDV0trbXh1UnlWSStIRUZUaEYyeDJNCllpVGtCQThFRnpiZ1FQN3h5LzRC
            cWxzQzFLUHd5WWlxNVczSzV0eFNJU1EKLS0tIFRvN2V2VEpnQWRoZmR1R294Wmt0
            dWIwajc2c0xJU2RxMEJUbzdoTjlPaWMKw+c+UZTkeqD06q4XyGyuRRQ+veDhzfhy
            qnzot3MxG0SQCQXFhDm9Ri4r3EA45CxC1+IvTWtRhwq+ABDVl/VnSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFZrL2ZXTGROcldPRDQ4
            bGhIZUE1TXBDQjVkMFhyRDQ3UGdVanMzc1ZJClFrQndmd2VMVmhVNFB0WVkxaGRP
            R1M3Q0loQWJSSUJrT0RJTEI2b2U5OUEKLS0tIGNMUlYvTy9WU0x0NEVFMDRKa2JD
            MU9ZRUlwbm1odUpSNDdqeGxYbE1iWFUK4fEt7q1Mnj6F8VR19GcS1ti1NXGIxA8N
            3+rTeuw09KWUYmhxQlJp6cXz8Ye8mDwi0pqKN2IRiQDtc2QEaJ3y7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T11:47:14Z"
    mac: ENC[AES256_GCM,data:Z2IwWnawwCbAXZd0jJk/MV6KHZkA4+LV3EfTRZv8n0yTEgaJmxcYVogyBZ+dl6fyqT9gigU64DrufY4J/3aaRQwX5UmupsdNLwT0xyiLQa0K6JjiWIRqn8wgDN5FHTFbIJE0bbsdNB1+jeMgNXfwX+tqpUIHVB651okw0hj62po=,iv:eDxl/XZVX9nG9DrJxZ+Xsep8wMZ04RT77qXYRQ+uEzo=,tag:sjTCpv67/1NW/XWbOelhwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://prometheus-community.github.io/helm-charts
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NU51RElrd29xWDM2T0hr
            UEc5cVVDV0trbXh1UnlWSStIRUZUaEYyeDJNCllpVGtCQThFRnpiZ1FQN3h5LzRC
            cWxzQzFLUHd5WWlxNVczSzV0eFNJU1EKLS0tIFRvN2V2VEpnQWRoZmR1R294Wmt0
            dWIwajc2c0xJU2RxMEJUbzdoTjlPaWMKw+c+UZTkeqD06q4XyGyuRRQ+veDhzfhy
            qnzot3MxG0SQCQXFhDm9Ri4r3EA45CxC1+IvTWtRhwq+ABDVl/VnSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFZrL2ZXTGROcldPRDQ4
            bGhIZUE1TXBDQjVkMFhyRDQ3UGdVanMzc1ZJClFrQndmd2VMVmhVNFB0WVkxaGRP
            R1M3Q0loQWJSSUJrT0RJTEI2b2U5OUEKLS0tIGNMUlYvTy9WU0x0NEVFMDRKa2JD
            MU9ZRUlwbm1odUpSNDdqeGxYbE1iWFUK4fEt7q1Mnj6F8VR19GcS1ti1NXGIxA8N
            3+rTeuw09KWUYmhxQlJp6cXz8Ye8mDwi0pqKN2IRiQDtc2QEaJ3y7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T11:47:14Z"
    mac: ENC[AES256_GCM,data:Z2IwWnawwCbAXZd0jJk/MV6KHZkA4+LV3EfTRZv8n0yTEgaJmxcYVogyBZ+dl6fyqT9gigU64DrufY4J/3aaRQwX5UmupsdNLwT0xyiLQa0K6JjiWIRqn8wgDN5FHTFbIJE0bbsdNB1+jeMgNXfwX+tqpUIHVB651okw0hj62po=,iv:eDxl/XZVX9nG9DrJxZ+Xsep8wMZ04RT77qXYRQ+uEzo=,tag:sjTCpv67/1NW/XWbOelhwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
            version: '*'
    interval: 1m0s
    values:
        grafana:
            enabled: true
            adminPassword: ENC[AES256_GCM,data:qQ7PHHwtAzRTNQapazaNZmhvsFi37+Cv,iv:KicSB2klNZrF/ZF1mluwRIqzj8Zl3jZXTVqxKBzcmLE=,tag:rfgd+fS/sQkotIYhxEx66Q==,type:str]
            service:
                type: ClusterIP
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - grafana.core-k8s.phorge.fr
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.core-k8s.phorge.fr
            persistence:
                enabled: true
                accessModes:
                    - ReadWriteOnce
                size: 1Gi
        prometheus:
            prometheusSpec:
                retention: 15d
                serviceMonitorSelector: {}
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqgndcckz7vshp69llrr3e5ypcy90xx3ufn0g9ymt3pgt9uzqaq3gn427
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NU51RElrd29xWDM2T0hr
            UEc5cVVDV0trbXh1UnlWSStIRUZUaEYyeDJNCllpVGtCQThFRnpiZ1FQN3h5LzRC
            cWxzQzFLUHd5WWlxNVczSzV0eFNJU1EKLS0tIFRvN2V2VEpnQWRoZmR1R294Wmt0
            dWIwajc2c0xJU2RxMEJUbzdoTjlPaWMKw+c+UZTkeqD06q4XyGyuRRQ+veDhzfhy
            qnzot3MxG0SQCQXFhDm9Ri4r3EA45CxC1+IvTWtRhwq+ABDVl/VnSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ynlvjztfcz8zfsddwj2c9cjdk0w3x3nmezamdld67c2489yuvavs09xar8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFZrL2ZXTGROcldPRDQ4
            bGhIZUE1TXBDQjVkMFhyRDQ3UGdVanMzc1ZJClFrQndmd2VMVmhVNFB0WVkxaGRP
            R1M3Q0loQWJSSUJrT0RJTEI2b2U5OUEKLS0tIGNMUlYvTy9WU0x0NEVFMDRKa2JD
            MU9ZRUlwbm1odUpSNDdqeGxYbE1iWFUK4fEt7q1Mnj6F8VR19GcS1ti1NXGIxA8N
            3+rTeuw09KWUYmhxQlJp6cXz8Ye8mDwi0pqKN2IRiQDtc2QEaJ3y7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T11:47:14Z"
    mac: ENC[AES256_GCM,data:Z2IwWnawwCbAXZd0jJk/MV6KHZkA4+LV3EfTRZv8n0yTEgaJmxcYVogyBZ+dl6fyqT9gigU64DrufY4J/3aaRQwX5UmupsdNLwT0xyiLQa0K6JjiWIRqn8wgDN5FHTFbIJE0bbsdNB1+jeMgNXfwX+tqpUIHVB651okw0hj62po=,iv:eDxl/XZVX9nG9DrJxZ+Xsep8wMZ04RT77qXYRQ+uEzo=,tag:sjTCpv67/1NW/XWbOelhwg==,type:str]
    pgp: []
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.9.1
